apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: acs-fleet-manager-rali
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: acs-fleet-manager-rali
    app.kubernetes.io/part-of: testapp
  name: acs-fleet-manager-rali
  namespace: dfodor-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: acs-fleet-manager-rali
    weight: 100
status: {}
